apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: story
  template:
    metadata:
      labels:
        app: story
    spec:
      containers:
        - name: story
          image: this888dockerkde/kub-data-demo:latest
          volumeMounts:
            - mountPath: /app/story # This is the path inside the container
              name: story-volume
      volumes:
        - name: story-volume
          hostPath:
            path: /data
            type: Directory
